repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-symlinks
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: no-commit-to-branch
      - id: pretty-format-json
        args: [--autofix]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs

#  - repo: https://github.com/pre-commit/mirrors-pylint
#    rev: v2.6.0
#    hooks:
#      - id: pylint
